<h2 class="title">Autentificare</h2>
<p class="meta">Completati campurile de mai jos pentru a va autentifica pe site</p>
<style type="text/css">label { display: block } .red { color: red; font-weight: bold }</style>
<div>
	<?php if (($_POST && !$page['login']) || !$_POST && !$page['loggedIn']): ?>
	<form method="post">
		<?php if($_POST): ?>
			<p style="color: red">Eroare la autentificare! Reincercati!</p>
		<?php endif; ?>
		<fieldset>
			<legend>Autentificare</legend>
			<br />
			<label>E-mail: <span class="red"><?php echo $page['errors']['email']; ?></span>
				<br /><input type="text" name="email" value="<?php echo $_POST['email']; ?>"></label>
			<br />
			<label>Parola: <span class="red"><?php echo $page['errors']['pass']; ?></span>
				<br /><input type="password" name="pass"></label>
			<br />
			<?php if (USE_RECAPTCHA): ?>
			<!-- <RECAPTCHA> --> 
			<div id="recaptcha_widget" style="display: none"> 
				Cod securitate: <span class="red"><?php echo $page['errors']['captcha']; ?></span><br /> 
				<input type="text" class="text-input" name="recaptcha_response_field" id="recaptcha_response_field" autocomplete="off" /> 
					<a style="margin-left: 20px; line-height: 20px" href="javascript:Recaptcha.reload()">Inteligibil? Click aici!</a> 
				<div id="recaptcha_image"></div> 
			</div> 
			<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script> 
			<script type="text/javascript"> 
			$(function() {
			 Recaptcha.create('6LfbxLoSAAAAAIMlK_LYv46Xej8Tfg7_tD5txT7c',
				'recaptcha_widget', { theme: 'custom' }
			  );
			});
			</script> 
			<!-- </RECAPTCHA> --> 		
			<?php endif; ?>
			<input type="submit" value="Logare" > <a href="/auth/register">Nu aveti cont? Creati unul aici!</a>
		</fieldset>
	</form>
	<?php elseif($page['login']): ?>
	<p>V-ati autentificat cu succes!</p>
	<p>Puteti folosi site-ul in continuare...</p>
	<?php elseif($page['loggedIn']): ?>
	<p>Sunteti deja logat(a) pe site!</p>
	<a href="/auth/logout">Delogare</a>
	<?php endif; ?>
</div>
