<h2 class="title">Inregistrare</h2>
<p class="meta">Creati un cont pentru a putea folosi mai bine site-ul nostru!</p>
<style type="text/css">
	.red { font-weight: bold; color :red }
</style>
<?php if ($_POST && $page['errors'] || !$_POST): ?>
<form method="post">
	<fieldset>
		<legend>Inregistrare</legend>
		<br />
			<label>Email: <span class="red"><?php echo $page['errors']['email']; ?>
				<br /><input type="text" name="email" value="<?php echo $_POST['email']; ?>"></label>
		<br />
			<label>Parola: <span class="red"><?php echo $page['errors']['password']; ?>
				<br /><input type="password" name="password"></label>
		<br />
			<label>Parola (verificare): <span class="red"><?php echo $page['errors']['password2']; ?>
				<br /><input type="password" name="password2"></label>
		<br />
		<?php if (USE_RECAPTCHA): ?>
		<!-- <RECAPTCHA> --> 
		<div id="recaptcha_widget" style="display: none"> 
			<label>Cod securitate: <span class="red"><?php echo $page['errors']['captcha']; ?><br /> 
				<input type="text" name="recaptcha_response_field" id="recaptcha_response_field" autocomplete="off" /> 
			</label>
				<a style="margin-left: 20px; line-height: 20px" href="javascript:Recaptcha.reload()">Inteligibil? Click aici!</a> 
			<div id="recaptcha_image"></div> 
		</div> 
		<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script> 
		<script type="text/javascript"> 
		$(function() {
		 Recaptcha.create('6LfbxLoSAAAAAIMlK_LYv46Xej8Tfg7_tD5txT7c',
			'recaptcha_widget', { theme: 'custom' }
		  );
		});
		</script> 
		<!-- </RECAPTCHA> --> 
		<?php endif; ?>
		<input type="submit" value="Inregistrare">
	</fieldset>
</form>
<?php else: ?>
<p>Felicitari, v-ati inregistrat!</p>
<p>Veti primi in scurt timp si un email de confirmare ce contine detaliile folosite la inregistrare!</p>

<br/><p>Va multumim!</p>
<?php endif; ?>