<h1>Goluri</h1>
<h2>Lista tuturor golurilor ale jucatorului selectat</h2>
<?php echo $page['paginare']; ?>
<table class="zebra">
	<tbody>
	<?php 
		if ($page['goals']):
		
		$lastMatchId = null;
		
		foreach($page['goals'] as $i => $r): 
			if ($lastMatchId != $r['meci_id']): ?>
			<tr></tr>
			<tr class="meciHeader">
				<th class="first"><?php echo $r['e1nume']; ?></th><th colspan="2"><?php echo $r['meci_data_ora']; ?></th>
					<th class="last"><?php echo $r['e2nume']; ?></th>
			</tr>
			<?php $lastMatchId = $r['meci_id']; endif; ?>
			<tr <?php if ($i%2) echo 'class="odd"'; ?>>
				<td></td>
				<td style="font-weight: bold; text-align: center"><?php echo $r['minutul']; ?>&quot;</td>
				<td><?php echo $r['jucator_nume']; ?> <span style="color: red"><?php echo $r['autogol']; ?></span></td>
				<td></td>
			</tr>
	<?php endforeach;
			endif; ?>
	</tbody>
</table>
<?php echo $page['paginare'];

//Zend_Debug::dump($page['goals']);