<style type="text/css">
	.contact em { color: red; font-weight: bold }
</style>
<h2 class="title"><a href="/statice/contact">Contact</a></h2>
<p class="meta"></p>
<?php if ($_POST && !count($page['errors']) ): ?>
<p>Mesajul dvs. a fost trimis cu succes, va multumim!</p>
<?php else: ?>

<form action="statice/contact" method="post">
	<fieldset style="width: 360px" class="contact">
	E-mail: <?php echo '<em>'.$page['errors']['mail'].'</em>'; ?>
	<br/><input type="text" name="mail" value="<?php echo $_POST['mail']; ?>"><br/>
	Subiect mesaj: <?php echo '<em>'.$page['errors']['subiect'].'</em>'; ?><br/>
	<input type="text" name="subiect" value="<?php echo $_POST['subiect']; ?>"><br/>		
	Mesaj: <?php echo '<em>'.$page['errors']['mesaj'].'</em>'; ?><br/> 
	<textarea name="mesaj" rows="6" cols="41"><?php echo $_POST['mesaj']; ?></textarea><br/><br/> 
	<!-- RECAPTCHA -->
	<div id="recaptcha_widget" style="display: none"> 
		Cod securitate: <?php echo '<em>'.$page['errors']['captcha'].'</em>'; ?><br />
		<input type="text" class="text-input" name="recaptcha_response_field" id="recaptcha_response_field" autocomplete="off" /> 
			<a style="margin-left: 20px; line-height: 20px" href="javascript:Recaptcha.reload()">Inteligibil? Click aici!</a> 
		<div id="recaptcha_image"></div> 
	</div> 
	<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script> 
	<script type="text/javascript"> 
	$(function() {
	 Recaptcha.create('<?php echo RECAPTCHA_PBL; ?>',
		'recaptcha_widget', { theme: 'custom' }
	  );
	});
	</script> 
	<!-- /RECAPTCHA -->
	<input type="submit" value="Trimite"> 
	</fieldset>
</form>
<?php endif; ?>